# Results

In [1]:
import duckdb
import pandas as pd
import sys
import spacy
import os
sys.path.append('..')

from src.utils import make_corpus, preprocess_spacy
from src.semantic import build_semantic_index, semantic_search
from src.bm25 import bm25_search, build_bm25

## Build Corpus and Preprocessing

In [2]:
# Read data and drop missing values
c2 = duckdb.connect()
data = c2.execute(f"SELECT * FROM read_parquet('../data/raw/merged.parquet')").df()
data.dropna(subset=['product_title'], inplace=True)

In [3]:
# Extract fields for retrieval
cols = ['product_title', 'main_category', 'store', 'title', 'text']

corpus = make_corpus(df=data, cols=cols, asin="asin")

In [4]:
# preprocess corpus and save it
os.makedirs('data/processed', exist_ok=True)

# if corpus is already processed and saved, pass to save time
corpus_path = "../data/processed/preprocessed_corpus.csv"
if os.path.exists(corpus_path):
    corpus = pd.read_csv(corpus_path)
else:
    nlp = spacy.load("en_core_web_md", disable=["parser", "ner"])
    corpus["text"] = [preprocess_spacy(text) for text in nlp.pipe(corpus["text"])]
    corpus.to_csv(corpus_path)

## Save Indices for BM25 and Embeddings

In [5]:
# BM25 index

pickle_path = "../data/processed/bm25.pkl"
bm25 = build_bm25(pickle_path, corpus)

In [6]:
# Semantic index 
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")
semantic_index_path = '../data/processed/embedding.faiss'

if not os.path.exists(semantic_index_path):
    build_semantic_index(corpus, model, semantic_index_path)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

# Retrieve Results

In [7]:
queries = ["Wet wipes",
           "Bar Soap",
           "Small hair dryer",
           "The best air humidifer with essential oil",
           "mineral sunscreen for babies",
           "hair spray that last more than 6 hours",
           "Best Vitamins or supplements to take for pregnant women",
           "best stainless steel pan for cooking",
           "sunrise lamp that will help me to wake up in the morning",
           "Something to relieve my back pain"]

In [8]:
for q in queries:
    print(f"QUERY: {q}\n")

    print("BM25 top results:")
    display(bm25_search(q, pickle_path, data))

    print("\nSemantic search top results:")
    display(semantic_search(q, semantic_index_path, model, data))

QUERY: Wet wipes

BM25 top results:

,product_title,text,rating,score
9003,Rolhei 75% Ethanol Wet Wipe - 2 Packs of 100 (...,that the wipes are thick and not thin.,5.0,15.452317
6634,Lens Wipes Pre-moistened Eye Glasses Cleaner W...,"I bought these based on the reviews, but they ...",1.0,12.032342
12808,"Pre-Moistened Lens Cleaning Wipes, Wet and Dry...",These were really wipes more for use in medica...,1.0,11.516642
6716,"Pre-Moistened Lens Cleaning Wipes, Wet and Dry...",What we liked most was that it does an excelle...,2.0,11.441593
15207,"Pre-Moistened Lens Cleaning Wipes, Wet and Dry...",Do not buy this item. The wipes are so small t...,1.0,10.531983

Semantic search top results:

,product_title,text,rating,score
460,Pampers Baby Fresh Water Baby Wipes 3X Pop-Top...,Baby wipes sure have improved since I used the...,5.0,0.920217
6634,Lens Wipes Pre-moistened Eye Glasses Cleaner W...,"I bought these based on the reviews, but they ...",1.0,0.876085
2377,Rinse Free Sponge Bath Wipes (30-pack) | Extra...,I was very pleased with these rinse-free bath ...,4.0,0.851884
4990,Wet-it Skrubba New European Scrubby Non-Scratc...,"Love these scrubbers, colorful and work well, ...",5.0,0.849512
230,Rinse Free Sponge Bath Wipes (30-pack) | Extra...,When you can't get in the shower and want to f...,4.0,0.840174

QUERY: Bar Soap

BM25 top results:

,product_title,text,rating,score
16384,Zero Waste Dish Washing Soap Bar Set (Cinnamon...,Love it. No mess. Works as well as liquid dish...,5.0,12.696275
4172,Zero Waste Dish Washing Soap Bar Set (Cinnamon...,I'm trying to find products to replace all the...,4.0,12.650885
12804,Dealglad 10Pcs Double Layer Exfoliating Mesh S...,Must have with bars of soap ! You will love !,5.0,12.193924
4991,Dial Corp. 04303 Fels-Naptha Laundry Bar Soap ...,I use this along with other soaps as an inexpe...,5.0,12.046332
4371,Bubble Shack Hawaii Loofah Soap Trio Organza S...,"I like these loofah soaps. These, however, see...",4.0,11.755763

Semantic search top results:

,product_title,text,rating,score
4371,Bubble Shack Hawaii Loofah Soap Trio Organza S...,"I like these loofah soaps. These, however, see...",4.0,0.808832
4991,Dial Corp. 04303 Fels-Naptha Laundry Bar Soap ...,I use this along with other soaps as an inexpe...,5.0,0.807457
16384,Zero Waste Dish Washing Soap Bar Set (Cinnamon...,Love it. No mess. Works as well as liquid dish...,5.0,0.794553
12804,Dealglad 10Pcs Double Layer Exfoliating Mesh S...,Must have with bars of soap ! You will love !,5.0,0.786824
2883,Dial Corp. 04303 Fels-Naptha Laundry Bar Soap ...,Mom used this soap and I use it now too. This ...,5.0,0.769150

QUERY: Small hair dryer

BM25 top results:

,product_title,text,rating,score
4112,JINRI Travel Hair Dryer 1875 Watt Dual Voltage...,Hairdryer is small and very compact. Good for ...,5.0,16.296875
18562,2 Pcs Home Portable Hair Dryer Diffuser Bonnet...,Love the bonnet. That piece works perfect. The...,4.0,15.492961
12826,JINRI Travel Hair Dryer 1875 Watt Dual Voltage...,I absolutely love this hair dryer. It's cute a...,5.0,15.083106
6443,"Hair Dryers, Ionic 1875W Portable Hair Blow Dr...",[[VIDEOID:efbc098d0c1d871b515eda2b6796d43d]] T...,5.0,14.975512
3,"Jinri Professional Tourmaline Hair Dryer, Nega...",This Jinri hair dryer is among one of the best...,5.0,14.701050

Semantic search top results:

,product_title,text,rating,score
4943,2 Pcs Home Portable Hair Dryer Diffuser Bonnet...,This thing is horrible. I can get over the fa...,1.0,0.774321
6443,"Hair Dryers, Ionic 1875W Portable Hair Blow Dr...",[[VIDEOID:efbc098d0c1d871b515eda2b6796d43d]] T...,5.0,0.737939
18885,JINRI Travel Hair Dryer 1875 Watt Dual Voltage...,"Very tiny and compact, but also quiet. My teen...",5.0,0.732036
15029,"Jinri Professional Tourmaline Hair Dryer, Nega...",[[VIDEOID:64f556223f7fbc7bd5cf7d55b2557181]] T...,5.0,0.727992
4112,JINRI Travel Hair Dryer 1875 Watt Dual Voltage...,Hairdryer is small and very compact. Good for ...,5.0,0.637268

QUERY: The best air humidifer with essential oil

BM25 top results:

,product_title,text,rating,score
2340,"Sandalwood Essential Oil 100ML,100% Pure Organ...",This is a pretty nice Vanilla fragrance oil. I...,4.0,12.399124
16601,US Organic 100% Pure Peppermint Essential Oil ...,This is a good carrier oil for my essential oi...,5.0,11.627170
12938,US Organic 100% Pure Peppermint Essential Oil ...,This oil smells so good! Just like a geranium ...,5.0,10.794896
4404,US Organic 100% Pure Peppermint Essential Oil ...,This Lavender essential oil seems very pure in...,5.0,10.759469
2773,Lemon Essential Oil 4 Oz - 5x Extra Strength 1...,This is a company I like to use for essential ...,5.0,10.685654

Semantic search top results:

,product_title,text,rating,score
16447,"Sandalwood Essential Oil 100ML,100% Pure Organ...",[[VIDEOID:837ed82f58e6aa8381af0ddfc97e2777]] T...,5.0,0.787273
17204,Top 8 Aromatherapy Essential Oil Starter Set- ...,really like it but....the oil is very light i ...,3.0,0.785169
6518,Aromyst Ultrasonic Glass Essential Oil Aromath...,I broke the first Aromyst I had by dropping it...,5.0,0.774747
2533,NEWSTYLE 700ml Large Capacity Aroma Atomizer A...,This is a very small unit. Do not expect this...,4.0,0.744626
8410,Lemon Essential Oil 4 Oz - 5x Extra Strength 1...,I love the citrus essential oils because they ...,5.0,0.727725

QUERY: mineral sunscreen for babies

BM25 top results:

,product_title,text,rating,score
16667,Tangy Tangerine - 420 G Canister Single,Dr. Wallach's products. This formula is simil...,5.0,10.190047
16923,SOLARICARE 60 Cap Bottle 240mg 20:1 whole herb...,Took it on trip to Cancun. Didn't notice anyth...,3.0,9.908568
11061,Avon SKIN-SO-SOFT Bug Guard PLUS IR3535® Insec...,This seems to work well as both a sunscreen an...,5.0,8.362735
8468,Daily's Min-Col® Fortè (250 Vegetarian Capsules),I have ordered these supplements several times...,5.0,8.322886
8698,North American Herb and Spice Mineral Suppleme...,I have been using a water machine to alkalize ...,5.0,8.047409

Semantic search top results:

,product_title,text,rating,score
16923,SOLARICARE 60 Cap Bottle 240mg 20:1 whole herb...,Took it on trip to Cancun. Didn't notice anyth...,3.0,0.977578
6269,Avon SKIN-SO-SOFT Bug Guard PLUS IR3535® Insec...,"I love this sunblock, we used it for 4 hours a...",5.0,0.977444
8483,"Burt's Bees Baby Nourishing Lotion, Calming Ba...",This has done wonders in helping to heal my ba...,5.0,0.938799
16503,"Bentonite, Hydrated (32 FL OZ)",Worked great,4.0,0.895416
8657,Amazon Brand - Solimo Petroleum Jelly White Pe...,Love the price. I use this in every diaper cha...,5.0,0.851749

QUERY: hair spray that last more than 6 hours

BM25 top results:

,product_title,text,rating,score
12729,"Apalus Hair Straightening Brush, Fast Natural ...",This brush is AMAZING! I have very thick color...,5.0,13.020623
17106,FRIZZ EASE HAIR SPRAY,"After I style my hair, I’ve noticed this spray...",5.0,11.884240
8317,"Automatic Curling Iron, Cordless Hair Curler w...",Dead On Arrival. I charged it for 8 hours at ...,1.0,10.155206
15037,CGR Anti Fog Spray for Glasses: (2pk) 2 oz Spr...,Was wondering how well this product would work...,5.0,9.981457
8579,"Hair Straightener, Flat Iron Steam Hair Straig...",Its smells like my hair is always burning and...,1.0,9.786347

Semantic search top results:

,product_title,text,rating,score
10333,10 Seconds - Disinfectant,"This stuff is quite strong, be sure to spray i...",5.0,1.046064
17106,FRIZZ EASE HAIR SPRAY,"After I style my hair, I’ve noticed this spray...",5.0,1.045197
12954,10 Seconds - Disinfectant,Tried different sprays and they only seemed to...,5.0,0.987821
8935,10 Seconds - Disinfectant,It is pricey compared to other older eating sp...,5.0,0.980955
12729,"Apalus Hair Straightening Brush, Fast Natural ...",This brush is AMAZING! I have very thick color...,5.0,0.950636

QUERY: Best Vitamins or supplements to take for pregnant women

BM25 top results:

,product_title,text,rating,score
2385,Best Earth Naturals Vision Support Formula Sup...,We were taking just the Lutein for our eyes an...,4.0,10.515914
119,Pink Stork Immune Support: Immunity Supplement...,"This is a good supplement with vitamin c, zinc...",4.0,9.916997
16662,5X Potent B Complex Vitamin Supplement - Made ...,Good,5.0,9.915766
18720,Pink Stork Immune Support: Immunity Supplement...,I got this for my mom to help her get her immu...,5.0,9.885142
8620,"Hyland's - Calc. Fluor 6x, 500 Tablets","I was skeptical kinda, I feel it really works ...",5.0,9.748558

Semantic search top results:

,product_title,text,rating,score
6,Amazon Elements Women’s One Daily Multivitamin...,This is my new favorite daily vitamin. Totally...,5.0,1.023650
37,Amazon Elements Women’s One Daily Multivitamin...,I just turned fifty recently and have been tak...,5.0,1.010174
12871,"GNC Women's Ultra Mega Active, 180 ea",I love these vitamins. I've been taking these...,5.0,0.961611
11035,LIBIDOX™ Hormone Balance for Women by Raw Fath...,I bought this to help with my hot flashes. It ...,5.0,0.957951
16587,Amazon Elements Women’s One Daily Multivitamin...,I thought I would try. They are large so if yo...,4.0,0.937836

QUERY: best stainless steel pan for cooking

BM25 top results:

,product_title,text,rating,score
12495,"2 Pieces Cast Iron Scrubber, Red Iron Pan Clea...",Heavy duty and easy to use and clean. Perfect...,5.0,17.564817
18976,HEAVY DUTY Stainless Steel Cleaner and Polish ...,"Was so hoping..... Actually, the stainless st...",4.0,17.245247
19057,"Mr Clean Magic Eraser Pads, 8 Count (Pack of 1)",What can you say about Magic Eraser? It gets t...,5.0,14.764774
4366,"Accmor Reusable Copper Drinking Straws, 18/8 S...",Thought they were going to be pure. copper. P...,2.0,13.895729
10572,13 Pieces Cast Iron Cleaner Set Include Stainl...,"Decent kit, but the bristles on my brush are a...",3.0,13.720724

Semantic search top results:

,product_title,text,rating,score
12495,"2 Pieces Cast Iron Scrubber, Red Iron Pan Clea...",Heavy duty and easy to use and clean. Perfect...,5.0,1.224258
12322,Personal Stainless Steel Cock Locker Dick Slav...,It works. but it's NOT STAINLESS STEEL. It's...,4.0,1.163815
18860,The Pink Stuff - The Miracle All Purpose Clean...,I bought a used stove from a friend to have st...,1.0,1.144251
255,"Method Stainless Steel Cleaner, Apple Orchard,...",Not sure why people are dissing this. I only ...,4.0,1.110649
18976,HEAVY DUTY Stainless Steel Cleaner and Polish ...,"Was so hoping..... Actually, the stainless st...",4.0,0.915850

QUERY: sunrise lamp that will help me to wake up in the morning

BM25 top results:

,product_title,text,rating,score
18956,Naturebright L6060 Per2 Led Daylight Lamp,I tried the Phillips previously (see review th...,4.0,14.145717
4475,"5-hour ENERGY Shot, Regular Strength Orange, 1...",I got what I needed to wake up and get out to ...,5.0,12.930527
6350,"Sleep Mask for Women and Men,3D Contoured Eye ...","Very comfortable, which surprised me! I love t...",5.0,12.274937
15081,Verilux Original Natural Spectrum Deluxe Floor...,I had one of these lamps for several years and...,5.0,11.553884
16576,Indus Classic Pine Himalayan Salt Crystal Lamp...,This was my first salt lamp. It is very well ...,5.0,11.356824

Semantic search top results:

,product_title,text,rating,score
18743,Verilux Original Natural Spectrum Deluxe Floor...,I was sitting on my bed last night doing some ...,5.0,1.059190
2847,Verilux Original Natural Spectrum Deluxe Floor...,"I bought this as a gift for my mom, it was at ...",4.0,1.023793
16576,Indus Classic Pine Himalayan Salt Crystal Lamp...,This was my first salt lamp. It is very well ...,5.0,1.013871
2796,Naturebright L6060 Per2 Led Daylight Lamp,This functions well as daylight alarm. It's be...,3.0,0.727630
18956,Naturebright L6060 Per2 Led Daylight Lamp,I tried the Phillips previously (see review th...,4.0,0.675205

QUERY: Something to relieve my back pain

BM25 top results:

,product_title,text,rating,score
491,Neck Stretcher Cervical Neck Traction Device O...,First time user. It took me a while a find out...,5.0,10.952530
12649,Shoulder Wrap Gel Ice Hot Cold Pack for Should...,"I use it alot, great product, helps relieve my...",5.0,10.870432
14553,ZSZBACE Posture Corrector Back Brace for Men a...,It help with my back pain,5.0,10.828765
671,Korean Red Ginseng Patch Powerstrip Energy Pai...,These patches really do relieve the pain. They...,5.0,10.687405
6944,Real Time Pain Relief George Foreman's Knockou...,This stuff does exactly what it says it will d...,5.0,10.650396

Semantic search top results:

,product_title,text,rating,score
10646,"REEHUT Foam Roller - (6""x36"") Firm High-Densit...",Is what your back muscles and spine will say!<...,5.0,0.847140
2599,Lower Back Stretcher Spine Board-Back Stretche...,This really gives a nice stretch. I use it on...,5.0,0.810345
12300,Genericb Back Massage Stretcher Arch Magic Mes...,A little to stiff for sore back muscles. need ...,4.0,0.758031
2628,Acupuncture Mat and Pillow Set-Relieve Your St...,Really helped with tension in my shoulders!,5.0,0.709054
4439,Large Heating and Cooling Reusable Wrap by Soo...,This absolutely what I have been looking for t...,5.0,0.699777