# Results

In [1]:
import duckdb
import pandas as pd
import sys
import spacy
import os
sys.path.append('..')

from src.preprocess import make_corpus_preprocess, make_clean_data
from src.semantic import build_semantic_index, semantic_search
from src.bm25 import bm25_search, build_bm25

In [ ]:
# load clean data
raw_data_path = '../data/raw/merged.parquet'
clean_data_path = "../data/processed/clean_data.csv"

if not os.path.exists(clean_data_path):
    make_clean_data(raw_data_path, clean_data_path)

clean_data = pd.read_csv(clean_data_path)

## Build Corpus and Preprocessing

In [ ]:
# if corpus is already processed and saved, pass to save time
corpus_path = "../data/processed/preprocessed_corpus.csv"
if not os.path.exists(corpus_path):
    make_corpus_preprocess(clean_data_path, corpus_path)

corpus = pd.read_csv(corpus_path)

## Save Indices for BM25 and Embeddings

In [4]:
# BM25 index

pickle_path = "../data/processed/bm25.pkl"
bm25 = build_bm25(pickle_path, corpus)

In [5]:
# Semantic index 
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")
semantic_index_path = '../data/processed/embedding.faiss'

if not os.path.exists(semantic_index_path):
    build_semantic_index(corpus, model, semantic_index_path)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

# Retrieve Results

In [6]:
# Set max width for results dataframe
pd.set_option('display.max_colwidth', 200)

In [7]:
queries = ["Wet wipes",
           "Bar Soap",
           "Small hair dryer",
           "The best air humidifer with essential oil",
           "mineral sunscreen for babies",
           "hair spray that last more than 6 hours",
           "Best Vitamins or supplements to take for pregnant women",
           "equipments for stretching at home",
           "sunrise lamp that will help me to wake up in the morning",
           "Something to relieve my back pain"]

In [8]:
for q in queries:
    print(f"QUERY: {q}\n")

    print("BM25 top results:")
    display(bm25_search(q, pickle_path, corpus))

    print("\nSemantic search top results:")
    display(semantic_search(q, semantic_index_path, model, corpus))

QUERY: Wet wipes

BM25 top results:

,product_title,review_text,rating,score
4426,Rolhei 75% Ethanol Wet Wipe - 2 Packs of 100 (200 Wipes),that the wipes are thick and not thin.,5.0,15.452317
3174,Lens Wipes Pre-moistened Eye Glasses Cleaner Wipes 120 Individually Packaged for Cleaning Glasses Sunglasses Computer Screens Touchscreens Monitors,"I bought these based on the reviews, but they are not wet enough. My optician said that the wetter the better when it comes to cleansing your glasses. In fact, he recommended a spray and cloth bet...",1.0,12.032342
6058,"Pre-Moistened Lens Cleaning Wipes, Wet and Dry Wipes 300 pcs, for Lens Eyeglasses Glasses Screen iPhone Cell Phone, Remove smudges and Dirt Effectively, no More Scratches Streaks Residue (300)",These were really wipes more for use in medical not full sheets for glasses.,1.0,11.516642
3256,"Pre-Moistened Lens Cleaning Wipes, Wet and Dry Wipes 300 pcs, for Lens Eyeglasses Glasses Screen iPhone Cell Phone, Remove smudges and Dirt Effectively, no More Scratches Streaks Residue (300)","What we liked most was that it does an excellent job of cleaning your eyeglasses, better than anything we have used, BUT it is a two part system. First you use the wet one, then the dry one. The ...",2.0,11.441593
7325,"Pre-Moistened Lens Cleaning Wipes, Wet and Dry Wipes 300 pcs, for Lens Eyeglasses Glasses Screen iPhone Cell Phone, Remove smudges and Dirt Effectively, no More Scratches Streaks Residue (300)",Do not buy this item. The wipes are so small they won't cover the lens. It's a pain that you need 2 wipes to try to clean your glasses. Save your money and buy some other product.,1.0,10.531983

Semantic search top results:

,product_title,review_text,rating,score
8276,"Pampers Baby Fresh Water Baby Wipes 3X Pop-Top Packs, 192 Count","These wipes are good for just about anything including your bum...lol. The scent is refreshing and not overpowering either. Plus, you can carry these anywhere for extra cleanliness. I highly recom...",5.0,0.940183
3626,"Travelon Hand Soap Toiletry Sheets, 50-Count",This did clean my clothes on a recent trip to Europe but then my sister used it and her hands we wet so it turned into a lump we had to just use. The direction very clearly state you must use wit...,5.0,0.938806
2185,"Pre-Moistened Lens Cleaning Wipes, Wet and Dry Wipes 300 pcs, for Lens Eyeglasses Glasses Screen iPhone Cell Phone, Remove smudges and Dirt Effectively, no More Scratches Streaks Residue (300)",One towel to clean and one to dry. What a pain.,1.0,0.917276
2290,"Pampers Baby Fresh Water Baby Wipes 3X Pop-Top Packs, 192 Count",Decent quality but I'll stick with huggies wipes.,4.0,0.897646
4426,Rolhei 75% Ethanol Wet Wipe - 2 Packs of 100 (200 Wipes),that the wipes are thick and not thin.,5.0,0.705773

QUERY: Bar Soap

BM25 top results:

,product_title,review_text,rating,score
7378,"Zero Waste Dish Washing Soap Bar Set (Cinnamon & Coffee) – Vegan Solid Dish Bars with Eco Friendly Plastic Free Packaging – 3.53 Oz (100g) Each, Pack of 2",Love it. No mess. Works as well as liquid dish soap 😊,5.0,12.696275
1845,"Zero Waste Dish Washing Soap Bar Set (Cinnamon & Coffee) – Vegan Solid Dish Bars with Eco Friendly Plastic Free Packaging – 3.53 Oz (100g) Each, Pack of 2",I'm trying to find products to replace all the plastic soaps. I liked these they just don't last very long so for the price it doesn't compete just yet with the plastic liquid soaps. I'll keep try...,4.0,12.650885
6054,Dealglad 10Pcs Double Layer Exfoliating Mesh Soap Saver Pouch Bubble Foam Net Handmade Soap Mesh Bag Body Facial Cleaning Tool,Must have with bars of soap ! You will love !,5.0,12.193924
2664,Dial Corp. 04303 Fels-Naptha Laundry Bar Soap (Pack of 8),I use this along with other soaps as an inexpensive laundry detergent. It works very well.,5.0,12.046332
2044,"Bubble Shack Hawaii Loofah Soap Trio Organza Set (3 Bars, Rainbow Set)","I like these loofah soaps. These, however, seemed like the loofah was placed too close to the edge. In the past, they were in the middle of the soap bar. But I like the soap, the scents and the pr...",4.0,11.755763

Semantic search top results:

,product_title,review_text,rating,score
844,Beautywin Soft Silicone Bath Brush，Baby Shower Exfoliating Body Scrubber Cleaning Massage Tool Bathroom Products for Adult Pet Clean Tools (Yellow),Soap just falls right out it feel nice but ur soap doesn’t stay in it at all I filled it up put it down the grave it again all of soap was where it was sitting,1.0,0.870233
2044,"Bubble Shack Hawaii Loofah Soap Trio Organza Set (3 Bars, Rainbow Set)","I like these loofah soaps. These, however, seemed like the loofah was placed too close to the edge. In the past, they were in the middle of the soap bar. But I like the soap, the scents and the pr...",4.0,0.862591
7378,"Zero Waste Dish Washing Soap Bar Set (Cinnamon & Coffee) – Vegan Solid Dish Bars with Eco Friendly Plastic Free Packaging – 3.53 Oz (100g) Each, Pack of 2",Love it. No mess. Works as well as liquid dish soap 😊,5.0,0.856919
1845,"Zero Waste Dish Washing Soap Bar Set (Cinnamon & Coffee) – Vegan Solid Dish Bars with Eco Friendly Plastic Free Packaging – 3.53 Oz (100g) Each, Pack of 2",I'm trying to find products to replace all the plastic soaps. I liked these they just don't last very long so for the price it doesn't compete just yet with the plastic liquid soaps. I'll keep try...,4.0,0.845450
6054,Dealglad 10Pcs Double Layer Exfoliating Mesh Soap Saver Pouch Bubble Foam Net Handmade Soap Mesh Bag Body Facial Cleaning Tool,Must have with bars of soap ! You will love !,5.0,0.716469

QUERY: Small hair dryer

BM25 top results:

,product_title,review_text,rating,score
1785,JINRI Travel Hair Dryer 1875 Watt Dual Voltage Blow Dryer Dc Motor Foldable Handle Lightweight Negative Ionic Folding Hair Dryer (Black),Hairdryer is small and very compact. Good for guest room and my guest live it. Takes up little space and drys fast.,5.0,16.296875
8437,2 Pcs Home Portable Hair Dryer Diffuser Bonnet Attachment Salon Hairdryer Hair Diffuser Hair Dryer Bonnet Soft Cap Silver Pink,Love the bonnet. That piece works perfect. The tube part that connects to the blow dryer is a bit small. It didn't fit the blow drier I had. I had to find another compact one for it.,4.0,15.492961
6076,JINRI Travel Hair Dryer 1875 Watt Dual Voltage Blow Dryer Dc Motor Foldable Handle Lightweight Negative Ionic Folding Hair Dryer (Black),I absolutely love this hair dryer. It's cute and sleek and fits nicely in my travel bags. It has enough power to dry my which was something I was concerned about. I would recommend this item to an...,5.0,15.083106
2983,"Hair Dryers, Ionic 1875W Portable Hair Blow Dryer Intelligent Temperature Heat & Wind Speed Settings Technology, Negative Ion Hairdryer with AC Motor for Hair Care with Diffuser for Travel, Home","[[VIDEOID:efbc098d0c1d871b515eda2b6796d43d]] They hair dryer came securely packaged it can with a cute velvet travel size bag, It is a digital blow dryer so you can control the temperature on the ...",5.0,14.975512
3,"Jinri Professional Tourmaline Hair Dryer, Negative Ionic Blow Dryer with Concentrator, Lightweight Low Noise 1875W DC Motor Fast Dry Hair Blow Dryer","This Jinri hair dryer is among one of the best I have ever owned. Strong and powerful, my hair dries super quick. It has varying speeds and heat levels which allows me to dry and style my hair at ...",5.0,14.701050

Semantic search top results:

,product_title,review_text,rating,score
5971,Ceramic Hair Dryer Fast Drying,"I really like this ionic hair dryer for quickly blow drying my hair. It's really lightweight which helps as it takes a while to fully dry my thick, wavy hair. I like that it comes with a diffuser ...",4.0,0.877840
6076,JINRI Travel Hair Dryer 1875 Watt Dual Voltage Blow Dryer Dc Motor Foldable Handle Lightweight Negative Ionic Folding Hair Dryer (Black),I absolutely love this hair dryer. It's cute and sleek and fits nicely in my travel bags. It has enough power to dry my which was something I was concerned about. I would recommend this item to an...,5.0,0.843469
7147,"Jinri Professional Tourmaline Hair Dryer, Negative Ionic Blow Dryer with Concentrator, Lightweight Low Noise 1875W DC Motor Fast Dry Hair Blow Dryer",[[VIDEOID:64f556223f7fbc7bd5cf7d55b2557181]] This JINRI hairdryer is super lightweight and easy to hold. It has 1875 watts with 2 speeds and 3 temperatures. It also has a cool shot button that is ...,5.0,0.831453
8760,JINRI Travel Hair Dryer 1875 Watt Dual Voltage Blow Dryer Dc Motor Foldable Handle Lightweight Negative Ionic Folding Hair Dryer (Black),"Very tiny and compact, but also quiet. My teenage son loves it!",5.0,0.766485
1785,JINRI Travel Hair Dryer 1875 Watt Dual Voltage Blow Dryer Dc Motor Foldable Handle Lightweight Negative Ionic Folding Hair Dryer (Black),Hairdryer is small and very compact. Good for guest room and my guest live it. Takes up little space and drys fast.,5.0,0.747452

QUERY: The best air humidifer with essential oil

BM25 top results:

,product_title,review_text,rating,score
1190,"Sandalwood Essential Oil 100ML,100% Pure Organic Sandalwood Essential Oils for Aromatherapy, Diffuser, Massage, Skin Care, Bath","This is a pretty nice Vanilla fragrance oil. It is a fragrance oil or blend, not an essential oil. There's no such thing as vanilla essential oil. In the world of vanilla, there are vanilla absolu...",4.0,12.399124
7595,US Organic 100% Pure Peppermint Essential Oil - USDA Certified Organic - 10 ml Pack of 2 - w/Improved caps and droppers (More Size Variations Available),This is a good carrier oil for my essential oils! Very moisturizing. I wasn't sure if it would have it's own smell but it doesn't really. Seems like a good price for what you get.,5.0,11.627170
6188,US Organic 100% Pure Peppermint Essential Oil - USDA Certified Organic - 10 ml Pack of 2 - w/Improved caps and droppers (More Size Variations Available),This oil smells so good! Just like a geranium flower. I used it to make a roller ball of FCO and Geranium Oil to roll on my face. I also put two drops of the oil on a silk flower I have in my car....,5.0,10.794896
2077,US Organic 100% Pure Peppermint Essential Oil - USDA Certified Organic - 10 ml Pack of 2 - w/Improved caps and droppers (More Size Variations Available),"This Lavender essential oil seems very pure in aroma, consistency and color. It does have the botanical name Lavandula Angustifolia on the bottle and the USDA Certified Organic seal. If you want t...",5.0,10.759469
1623,Lemon Essential Oil 4 Oz - 5x Extra Strength 100% Pure & Natural Therapeutic Grade - Cold Pressed PREMIUM QUALITY Oil from Italy,This is a company I like to use for essential oils. I get some really nice products at really nice prices. I have tried alot of other companies but this one has some of the best quality oils I hav...,5.0,10.685654

Semantic search top results:

,product_title,review_text,rating,score
3968,"Rose Essential Oils Organic Plant & Natural 100% Pure Rose Oil for Diffuser, Humidifier, Massage, Sleep, Perfume, Bath, SPA, Skin & Hair Care-10ml…",Im so in loveee smell sooo good,5.0,0.787400
2115,Lemon Essential Oil 4 Oz - 5x Extra Strength 100% Pure & Natural Therapeutic Grade - Cold Pressed PREMIUM QUALITY Oil from Italy,Perfect fragrance for my kitchen. Quality product that lasts and does not clog my diffuser.,5.0,0.783801
3134,"Top 8 Aromatherapy Essential Oil Starter Set- Peppermint, Tea Tree, Rosemary, Orange, Lemongrass, Lavender, Eucalyptus & Frankincense.8/10ml","I was not a fan of this oil set. I use Doterra Oils but bought a blend set to use at work however all of these smell terrible and I can tell the quality is not great, probably because I am used to...",1.0,0.773630
305,"Sandalwood Essential Oil, MAYJAM Premium Pure Essential Oils, 3.38FL.OZ Sandalwood Oil for Diffusers Soap Candle Making, Ideal for Home Office Car Yoga Use",Love this! It smells amazing! Very good quality oil and it made my house smell great when I put it in my diffuser! You definitely have to try this one! The bottle was very well packaged and they p...,5.0,0.765910
3861,"Aromatherapy Top 20 Essential Oil, 100% PURE & NATURAL Therapeutic Grade Essential Oils-Most Popular Scents Essential Oil for Diffuser, Humidifier, Massage, Skin & Hair Care (Geranium)",The lid is cracked and leaked all of the liquid out poor packing and broken lid had to throw away not happy I wouldn’t recommend this product,1.0,0.680263

QUERY: mineral sunscreen for babies

BM25 top results:

,product_title,review_text,rating,score
7661,Tangy Tangerine - 420 G Canister Single,"Dr. Wallach's products. This formula is similar to other high grade formulas except this one has something called &#34;rare earth&#34; in it, I believe. Translated that means trace minerals. No...",5.0,10.190047
7917,SOLARICARE 60 Cap Bottle 240mg 20:1 whole herb extract of polypodium leucotomos,Took it on trip to Cancun. Didn't notice anything different vs. not using it. Can't say whether it helped. The capsules were tiny and easy to swallow. No taste or ill effects.<br /><br />Used suns...,3.0,9.908568
5431,"Avon SKIN-SO-SOFT Bug Guard PLUS IR3535® Insect Repellent Moisturizing Lotion - SPF 30 Gentle Breeze, 4 oz",This seems to work well as both a sunscreen and sand flea repellent for my sensitive-skinned 5-yr.-old. He gets quite a painful burning sensation from some other sunscreens but is not bothered by ...,5.0,8.362735
3891,Daily's Min-Col® Fortè (250 Vegetarian Capsules),I have ordered these supplements several times. They always come quickly and are a very easily absorbed calcium with other trace minerals.,5.0,8.322886
4121,"North American Herb and Spice Mineral Supplement Purely-Min, 5 Ounce",I have been using a water machine to alkalize and purity the water for several years. My research shows that it removes many minerals along with the chlorine and fluoride which is why I purchased...,5.0,8.047409

Semantic search top results:

,product_title,review_text,rating,score
8761,Equate Pure Cornstarch Baby Powder Aloe Vera and Vitamin E (15 oz 2 Pack),My husband prefers this powder to any other out their.,5.0,1.064018
4100,"Amazon Brand - Solimo Petroleum Jelly White Petrolatum Skin Protectant, Unscented, 7.5 Ounce",Make sure you don't buy a baby product because the smell will drive you crazy.,5.0,0.966073
7497,"Bentonite, Hydrated (32 FL OZ)",Worked great,4.0,0.933010
54,"Amazon Brand - Solimo Petroleum Jelly White Petrolatum Skin Protectant, Unscented, 7.5 Ounce","Generic brand of Vaseline. Seems to be identical to name brand. Multipurpose and handy to have on hand. I have tried one other product from Solimo, a spray sunscreen, and have been very happy with...",5.0,0.931844
3906,"Burt's Bees Baby Nourishing Lotion, Calming Baby Lotion - 6 Ounce Tube",This has done wonders in helping to heal my babies dry eczema prone skin! I alternate between this and mustella for eczema prone skin and now her skin is super soft and supple. No more dry flakey ...,5.0,0.914551

QUERY: hair spray that last more than 6 hours

BM25 top results:

,product_title,review_text,rating,score
5979,"Apalus Hair Straightening Brush, Fast Natural Straight Hair Styling, Anion Hair Care, Anti Scald, Massage Straightening Irons, Detangling Hair Brush","This brush is AMAZING! I have very thick color treated wavy shoulder length hair and I can honestly say that when I used this brush for the first time it only took me 10 minutes to straighten, ver...",5.0,13.020623
8100,FRIZZ EASE HAIR SPRAY,"After I style my hair, I’ve noticed this spray keeps it looking fuller all day. I have thick hair but this makes it appear to be twice it’s thickness. It keeps the style much longer than any oth...",5.0,11.884240
3740,"Automatic Curling Iron, Cordless Hair Curler with Adjustable Temperatures & Timers, Portable Auto Rotating Hair Curlers Wave Curling Wand, Rechargeable Ceramic Electric Hair Styling Tool","Dead On Arrival. I charged it for 8 hours at first, then tried it and it didn't turn on. The light turned on when it's charging so it wasn't the charger. I saw a Brad Mondo vid and his didn't t...",1.0,10.155206
7155,"CGR Anti Fog Spray for Glasses: (2pk) 2 oz Spray | Prevents Fog on All Lenses and Glasses, Sunglasses, Goggles, PPE | Safe on All Lenses | DEFOG it (2PK)",Was wondering how well this product would work but needed to use something whenever I would go out. Gave one bottle to my daughter-in-law to try out as well. She uses hers every day while at work....,5.0,9.981457
4002,"Hair Straightener, Flat Iron Steam Hair Straightener Nano Titanium Ceramic Tourmaline Flat Iron for Hair Travel Salon, 2 Inch White Professional Infrared Dual Voltage Hair Straightener by Megainvo",Its smells like my hair is always burning and the plates don't seem to keep my hair straight for more then a few hours,1.0,9.786347

Semantic search top results:

,product_title,review_text,rating,score
6649,OSIR Professional Automatic Studio Salon Ceramic Hair Curler with Negative Iron and LCD Display -- a Better Hair Style Maker (Flash Purple),I've spent much time trying this product out before reviewing and I've also tried the fo air curler secret. I watched videos and read the instructions and prepped my hair properly etc. it is essen...,3.0,1.106454
2782,California Baby Calming Detangler Spray | Plant-Based | Detangles Hair & Adds Shine | Light Lavender Scent | Allergy-Friendly | Gentle Leave in Conditioner Spray | 251 mL / 8.5 fl. oz.,"We do not use anything else. Nothing compares. Love it, just a bit more expensive but worth it. Hair doesn't get sticky. Goes on light. I do wish there was no odor. Daughter freaks out about brea...",5.0,1.101261
8100,FRIZZ EASE HAIR SPRAY,"After I style my hair, I’ve noticed this spray keeps it looking fuller all day. I have thick hair but this makes it appear to be twice it’s thickness. It keeps the style much longer than any oth...",5.0,1.097599
3867,OSiS+ by Schwarzkopf Buff Styling Cream 150ml,This is a great product for my long hair. Nothing else works for me. Thank God I found it on Amazon!,5.0,1.080452
3162,"Salon Graphix 404152 Extra Super Hold Shaping Hair Spray, 1.5 oz","This is 3 ounces, NOT 3 pounds! But came on time and its great for travel.",4.0,1.058336

QUERY: Best Vitamins or supplements to take for pregnant women

BM25 top results:

,product_title,review_text,rating,score
1235,"Best Earth Naturals Vision Support Formula Supplement with Eye Vitamins, Lutein, Vitamin A, Quercetin and More - 30 Count","We were taking just the Lutein for our eyes and found this which has more beneficial ingreds for our ""older"" eyes :) The Lutein helps a lot but didn't know that Vit A, Zinc, Taurine, etc, were he...",4.0,10.515914
119,"Pink Stork Immune Support: Immunity Supplements + Vitamin C, Zinc Vitamins for Adults, Immunity Vitamins & Antioxidants, Cough & Cold Relief, Womens Multivitamin, Women-Owned, 60 Capsules","This is a good supplement with vitamin c, zinc, and magnesium along with a blend of herbs. The capsules are easy to swallow. Because of the magnesium, I take it at night since magnesium can make y...",4.0,9.916997
7656,"5X Potent B Complex Vitamin Supplement - Made in USA - All B Vitamins Including Vitamin B12, Folic Acid, B1, B2, B3, B5, B6, and B7 - Supplement for Energy, Stress, Brain Function and Immune Support",Good,5.0,9.915766
8595,"Pink Stork Immune Support: Immunity Supplements + Vitamin C, Zinc Vitamins for Adults, Immunity Vitamins & Antioxidants, Cough & Cold Relief, Womens Multivitamin, Women-Owned, 60 Capsules",I got this for my mom to help her get her immune system stronger since things are going crazy with the pandemic and the upcoming cold and flu season,5.0,9.885142
4043,"Hyland's - Calc. Fluor 6x, 500 Tablets","I was skeptical kinda, I feel it really works actually. I think this and evening primrose an magnesium citrate help me get pregnant. I had extreme infertility problems took 5 years to get pregnant...",5.0,9.748558

Semantic search top results:

,product_title,review_text,rating,score
7581,"Amazon Elements Women’s One Daily Multivitamin, 59% Whole Food Cultured, Vegan, 65 Tablets, 2 month supply (Packaging may vary)",I thought I would try. They are large so if you struggle to swallow big pills than these are not for you. The ingredients seem natural and quality but not sure how you really rate vitamins working...,4.0,1.041810
8590,"Vitamin D3 5000iu Tablets, Super-Strong Immune System Boost. Great Value with 180 Tablets (6 Months Supply)","Much needed for these crazy times, helps me not be so fatigued from a vitamin d deficiency",5.0,1.035355
1246,"Wellmo Natural Vitamin D3 Soft Gels in Fast-Absorbing Coconut Oil for Men, Women, and Children - All-Natural, Vitamin D3 for Bone, Skin, and Immune Health - 60 Soft Gels (60 Day Supply)","Even being in the sun a lot, my blood work always shows me a little low on Vit D.<br />I like these pills. Nice and small to swallow. Helps boost my Vit D levels so there's no concerns.<br />I l...",5.0,1.018518
5405,LIBIDOX™ Hormone Balance for Women by Raw Fathers | Female Enhancement Pill - Female PMS PMDD Support | Herbal Vitamins for Women Health | 60 Capsules Made in USA,"I bought this to help with my hot flashes. It is definitely staying in my arsenal for my fight with menopause!<br /><br />I'm having a horrible time with hot flashes, and this has cut the amount i...",5.0,0.995874
1710,Vitamin D3 * Ultra Strength D-3 - K-2 ** Non GMO- Formula Give You UP to 6000IU Per Day,best ever,5.0,0.955704

QUERY: equipments for stretching at home

BM25 top results:

,product_title,review_text,rating,score
3014,Dixie EMS Dixigear Empty First Responder II Bag,I bought 2 in different colors. One holds a nebulizer and all its parts in one place. The other holds personal home medical equipment. No more bulky boxes. The different colors helps separate ...,5.0,8.983292
3015,Dixie EMS Dixigear Empty First Responder II Bag,"I needed something to keep my medical stuff in at home. This is holding 2 BP machines, O2 meter, glucometer in the outer pockets plus a few other things. I like to be organized and have ""like"" t...",5.0,8.380817
5766,"BSN Medical Cover Roll Stretch, 2"" x 10 yds, Single Roll",Just what I need for under some stretch wraps,5.0,8.096906
5199,Quattro FX Full Face Headgear - Small - 61734,"Works like it should. I normally wear medium, but they stretch out pretty fast, so I bought the small, which almost didn't fit, but after it stretched out, now it is just right. Very tight to star...",5.0,7.621536
159,"BSN Medical Cover Roll Stretch, 2"" x 10 yds, Single Roll",Keeps my skin safe from the luekotape I put over the cover roll stretch tape,5.0,7.621536

Semantic search top results:

,product_title,review_text,rating,score
1966,"Tune Up Fitness – Alpha Twin Set in Tote | Larger Sized Yoga Massage Therapy Balls | Deep Precision Rolling, Myofascial Release and Pain Relief for Upper & Lower Back, IT Band, QL, Hamstrings, Glutes",Perfect. I bought these on the recommendation of Kelly Starrett from his book Ready to Run.<br />They are exactly what I wanted. Sturdy and well made.,5.0,0.888051
6515,"5 x Spring Button Pant Waistband Extenders - Sturdy, Stretchy & Rust Proof","They are too flexible, they stretch out and don't work like I thought they would. Get the rigid plastic ones, they perform better.",1.0,0.883041
5956,"Tune Up Fitness – Alpha Twin Set in Tote | Larger Sized Yoga Massage Therapy Balls | Deep Precision Rolling, Myofascial Release and Pain Relief for Upper & Lower Back, IT Band, QL, Hamstrings, Glutes",great product. helps tremendously working out knots in my muscles. The Roll Model by Jill Miller gives detailed instructions on how to best use.,5.0,0.830649
5734,"Back Stretcher, Lumbar Relief Back Stretcher, Back Stretcher for Pain Relief, Multi-Level Back Stretching Device, Lower Back Stretcher Device, Back Massage Stretcher with 3 Adjustable Settings…",Do a good job of allowing the back to stretch but it hurts.. the plastic pokes so use a towel!,4.0,0.825025
7561,"Back Massager, Aptoco Back Stretcher for Sciatica Relief, Herniated Disc/Spinal Stenosis-Back Massage Stretcher, Back Stretching Device",A little uncomfortable for me (not very flexable) but my wife loves it and uses it multiple times a day.,4.0,0.793373

QUERY: sunrise lamp that will help me to wake up in the morning

BM25 top results:

,product_title,review_text,rating,score
8831,Naturebright L6060 Per2 Led Daylight Lamp,"I tried the Phillips previously (see review there) but just couldn't get it to work. The NatureBright is easy to figure out, the controls make a lot more sense and you can easily see that it's se...",4.0,14.145717
2148,"5-hour ENERGY Shot, Regular Strength Orange, 1.93 oz., 24 pack",I got what I needed to wake up and get out to my commute while it's still dark. I am the poster child for &#34;not a morning person.&#34; This makes it happen.,5.0,12.930527
2890,"Sleep Mask for Women and Men,3D Contoured Eye Mask for Sleeping Mask Eye Cover,Lightweight Sleep Masks Blindfolds Eye Shade for Kids Girls Travel,2 Pack Black","Very comfortable, which surprised me! I love that it doesn't press against your eyes. I also suffer from extremely dry eyes, especially in the morning when I wake up, due to multiple fans running ...",5.0,12.274937
7199,"Verilux Original Natural Spectrum Deluxe Floor Lamp, Ivory",I had one of these lamps for several years and liked for reading. As I consider it a fairly expensive lamp I was disappointed when the switch quit working. I didn't get a response when I contact...,5.0,11.553884
7570,Indus Classic Pine Himalayan Salt Crystal Lamp Natural Ion Theray 2.25 Kg,"This was my first salt lamp. It is very well made, interesting to look at and a nice solid size. It lights up really well. The photo on amazon doesn't do it justice IMO and makes it look like t...",5.0,11.356824

Semantic search top results:

,product_title,review_text,rating,score
1996,Naturebright L6060 Per2 Led Daylight Lamp,A+ However a bit difficult to program.,4.0,1.079733
1697,"Verilux Original Natural Spectrum Deluxe Floor Lamp, Ivory","I bought this as a gift for my mom, it was at the very least a bit of a pain to put together and cheaply made. It required electrical tape and a good bit of cursing! Is now working ok. The gril...",4.0,1.073756
537,"C&A Scientific Alcohol Lamp, Metal, Wickless, 100ml (97-5320)",The upside is that this is a very well made little lamp.<br />it's easy to start and produces a hot and steady flame.<br />If you need a light duty flame hot enough to heat a test tube or steriliz...,4.0,1.060951
1646,Naturebright L6060 Per2 Led Daylight Lamp,"This functions well as daylight alarm. It's best feature is that the LED's arc out over the bed and shine down, as opposed to other models which shine straight out horizontally, which means you ha...",3.0,1.048516
8831,Naturebright L6060 Per2 Led Daylight Lamp,"I tried the Phillips previously (see review there) but just couldn't get it to work. The NatureBright is easy to figure out, the controls make a lot more sense and you can easily see that it's se...",4.0,0.732633

QUERY: Something to relieve my back pain

BM25 top results:

,product_title,review_text,rating,score
491,"Neck Stretcher Cervical Neck Traction Device Over Door for Home Use,Portable Neck Traction for Neck Pain Relief, Physical Therapy AIDS for Neck Spine Decompressor (Black)",First time user. It took me a while a find out how to assemble them. After some adjustments I find a way to use it. And it does helps relieve my neck pain.,5.0,10.952530
5899,Shoulder Wrap Gel Ice Hot Cold Pack for Shoulder Injury Pain Relief Therapy Rotator Cuff Rheumatoid Arthritis Treatment Osteoarthritis Bursitis Tendinitis AC Joint Sports Injuries,"I use it alot, great product, helps relieve my muscle pain.",5.0,10.870432
6671,"ZSZBACE Posture Corrector Back Brace for Men and Women- Relieve Back Pain, Align Spain, Correct Kyphosis (XXL)",It help with my back pain,5.0,10.828765
671,Korean Red Ginseng Patch Powerstrip Energy Pain Relief - 20 Patches,These patches really do relieve the pain. They can be cut to whatever size you need.They stick extremely well.,5.0,10.687405
3484,"Real Time Pain Relief George Foreman's Knockout Formula, 1 Oz GoPak",This stuff does exactly what it says it will do. Relieve pain and make you feel better. Happy!,5.0,10.650396

Semantic search top results:

,product_title,review_text,rating,score
1449,"Lower Back Stretcher Spine Board-Back Stretcher for Lower Back Pain Relief, Back Cracking Device, Sciatica, Scoliosis, Spine Deck, on Bed,on Chair, Yoga Mat & Car-Spine Stretcher",This really gives a nice stretch. I use it on my office chair daily. Ever since I started using this the lower back pain I would have at the end of the day is gone.,5.0,0.939688
8077,"CareU(™) Coccyx Orthopedic Portable Comfort Memory Foam Seat Cushion with Non Slip Cover- Helps Relieve Kyphotic, Hip and Sciatica Pain (Standard Size 17.7x15 Inch)",I'm sitting on it right now. love it,5.0,0.923567
1478,"Acupuncture Mat and Pillow Set-Relieve Your Stress, Back, Neck, and Sciatic Pain(99% Cotton Fabric, Plastic Spikes and Foam core) Green",Really helped with tension in my shoulders!,5.0,0.918509
7561,"Back Massager, Aptoco Back Stretcher for Sciatica Relief, Herniated Disc/Spinal Stenosis-Back Massage Stretcher, Back Stretching Device",A little uncomfortable for me (not very flexable) but my wife loves it and uses it multiple times a day.,4.0,0.910006
5550,"Genericb Back Massage Stretcher Arch Magic Message Stretcher Back Stretcher Lumbar Support Device, Lower and Upper Back Pain Relief Relax Mate Spine Pain Relief Chiropractic",A little to stiff for sore back muscles. need to use a soft pad with it,4.0,0.852649