# Results

In [1]:
import duckdb
import pandas as pd
import sys
import spacy
import os
sys.path.append('..')

from src.utils import make_corpus, preprocess_spacy
from src.semantic import build_semantic_index, semantic_search
from src.bm25 import bm25_search, build_bm25

## Build Corpus and Preprocessing

In [2]:
# Read data and drop missing values
c2 = duckdb.connect()
data = c2.execute(f"SELECT * FROM read_parquet('../data/raw/merged.parquet')").df()
data.dropna(subset=['product_title'], inplace=True)

In [3]:
# Extract fields for retrieval
cols = ['product_title', 'main_category', 'store', 'title', 'text']

corpus = make_corpus(df=data, cols=cols, asin="asin")

In [4]:
# preprocess corpus and save it
os.makedirs('data/processed', exist_ok=True)

# if corpus is already processed and saved, pass to save time
corpus_path = "../data/processed/preprocessed_corpus.csv"
if os.path.exists(corpus_path):
    corpus = pd.read_csv(corpus_path)
else:
    nlp = spacy.load("en_core_web_md", disable=["parser", "ner"])
    corpus["text"] = [preprocess_spacy(text) for text in nlp.pipe(corpus["text"])]
    corpus.to_csv(corpus_path)

## Save Indices for BM25 and Embeddings

In [5]:
# BM25 index

pickle_path = "../data/processed/bm25.pkl"
bm25 = build_bm25(pickle_path, corpus)

In [6]:
# Semantic index 
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")
semantic_index_path = '../data/processed/embedding.faiss'

if not os.path.exists(semantic_index_path):
    build_semantic_index(corpus, model, semantic_index_path)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

# Retrieve Results

In [7]:
# Set max width for results dataframe
pd.set_option('display.max_colwidth', 200)

In [8]:
queries = ["Wet wipes",
           "Bar Soap",
           "Small hair dryer",
           "The best air humidifer with essential oil",
           "mineral sunscreen for babies",
           "hair spray that last more than 6 hours",
           "Best Vitamins or supplements to take for pregnant women",
           "equipments for stretching at home",
           "sunrise lamp that will help me to wake up in the morning",
           "Something to relieve my back pain"]

In [9]:
for q in queries:
    print(f"QUERY: {q}\n")

    print("BM25 top results:")
    display(bm25_search(q, pickle_path, data))

    print("\nSemantic search top results:")
    display(semantic_search(q, semantic_index_path, model, data))

QUERY: Wet wipes

BM25 top results:

,product_title,text,rating,score
9003,Rolhei 75% Ethanol Wet Wipe - 2 Packs of 100 (200 Wipes),that the wipes are thick and not thin.,5.0,15.452317
6634,Lens Wipes Pre-moistened Eye Glasses Cleaner Wipes 120 Individually Packaged for Cleaning Glasses Sunglasses Computer Screens Touchscreens Monitors,"I bought these based on the reviews, but they are not wet enough. My optician said that the wetter the better when it comes to cleansing your glasses. In fact, he recommended a spray and cloth bet...",1.0,12.032342
12808,"Pre-Moistened Lens Cleaning Wipes, Wet and Dry Wipes 300 pcs, for Lens Eyeglasses Glasses Screen iPhone Cell Phone, Remove smudges and Dirt Effectively, no More Scratches Streaks Residue (300)",These were really wipes more for use in medical not full sheets for glasses.,1.0,11.516642
6716,"Pre-Moistened Lens Cleaning Wipes, Wet and Dry Wipes 300 pcs, for Lens Eyeglasses Glasses Screen iPhone Cell Phone, Remove smudges and Dirt Effectively, no More Scratches Streaks Residue (300)","What we liked most was that it does an excellent job of cleaning your eyeglasses, better than anything we have used, BUT it is a two part system. First you use the wet one, then the dry one. The ...",2.0,11.441593
15207,"Pre-Moistened Lens Cleaning Wipes, Wet and Dry Wipes 300 pcs, for Lens Eyeglasses Glasses Screen iPhone Cell Phone, Remove smudges and Dirt Effectively, no More Scratches Streaks Residue (300)",Do not buy this item. The wipes are so small they won't cover the lens. It's a pain that you need 2 wipes to try to clean your glasses. Save your money and buy some other product.,1.0,10.531983

Semantic search top results:

,product_title,text,rating,score
460,"Pampers Baby Fresh Water Baby Wipes 3X Pop-Top Packs, 192 Count",Baby wipes sure have improved since I used them on my daughter who is now an adult. Many options are available now and there are noticeable differences among the offerings in the marketplace. I ...,5.0,0.920217
6634,Lens Wipes Pre-moistened Eye Glasses Cleaner Wipes 120 Individually Packaged for Cleaning Glasses Sunglasses Computer Screens Touchscreens Monitors,"I bought these based on the reviews, but they are not wet enough. My optician said that the wetter the better when it comes to cleansing your glasses. In fact, he recommended a spray and cloth bet...",1.0,0.876085
2377,Rinse Free Sponge Bath Wipes (30-pack) | Extra Large & Thick No Rinse Waterless Body Wipe Sponges - Disposable Shower Cleaning Wash Cloths for Kids Adults Surgery Elder Care Gym Travel & More (1 P...,"I was very pleased with these rinse-free bath cloths by Nurture. They are larger than I expected, thick and soft. With just a little bit of water and a couple squeezes, they produce a nice lather ...",4.0,0.851884
4990,"Wet-it Skrubba New European Scrubby Non-Scratching Scouring Pads (Set of 3, Stripe Chicken Paisley)","Love these scrubbers, colorful and work well, NOT scented",5.0,0.849512
230,Rinse Free Sponge Bath Wipes (30-pack) | Extra Large & Thick No Rinse Waterless Body Wipe Sponges - Disposable Shower Cleaning Wash Cloths for Kids Adults Surgery Elder Care Gym Travel & More (1 P...,When you can't get in the shower and want to feel refreshed or just clean these are really good to have around. Thick enough that you won't easily drive your fingers through the material but thin ...,4.0,0.840174

QUERY: Bar Soap

BM25 top results:

,product_title,text,rating,score
16384,"Zero Waste Dish Washing Soap Bar Set (Cinnamon & Coffee) – Vegan Solid Dish Bars with Eco Friendly Plastic Free Packaging – 3.53 Oz (100g) Each, Pack of 2",Love it. No mess. Works as well as liquid dish soap 😊,5.0,12.696275
4172,"Zero Waste Dish Washing Soap Bar Set (Cinnamon & Coffee) – Vegan Solid Dish Bars with Eco Friendly Plastic Free Packaging – 3.53 Oz (100g) Each, Pack of 2",I'm trying to find products to replace all the plastic soaps. I liked these they just don't last very long so for the price it doesn't compete just yet with the plastic liquid soaps. I'll keep try...,4.0,12.650885
12804,Dealglad 10Pcs Double Layer Exfoliating Mesh Soap Saver Pouch Bubble Foam Net Handmade Soap Mesh Bag Body Facial Cleaning Tool,Must have with bars of soap ! You will love !,5.0,12.193924
4991,Dial Corp. 04303 Fels-Naptha Laundry Bar Soap (Pack of 8),I use this along with other soaps as an inexpensive laundry detergent. It works very well.,5.0,12.046332
4371,"Bubble Shack Hawaii Loofah Soap Trio Organza Set (3 Bars, Rainbow Set)","I like these loofah soaps. These, however, seemed like the loofah was placed too close to the edge. In the past, they were in the middle of the soap bar. But I like the soap, the scents and the pr...",4.0,11.755763

Semantic search top results:

,product_title,text,rating,score
4371,"Bubble Shack Hawaii Loofah Soap Trio Organza Set (3 Bars, Rainbow Set)","I like these loofah soaps. These, however, seemed like the loofah was placed too close to the edge. In the past, they were in the middle of the soap bar. But I like the soap, the scents and the pr...",4.0,0.808832
4991,Dial Corp. 04303 Fels-Naptha Laundry Bar Soap (Pack of 8),I use this along with other soaps as an inexpensive laundry detergent. It works very well.,5.0,0.807457
16384,"Zero Waste Dish Washing Soap Bar Set (Cinnamon & Coffee) – Vegan Solid Dish Bars with Eco Friendly Plastic Free Packaging – 3.53 Oz (100g) Each, Pack of 2",Love it. No mess. Works as well as liquid dish soap 😊,5.0,0.794553
12804,Dealglad 10Pcs Double Layer Exfoliating Mesh Soap Saver Pouch Bubble Foam Net Handmade Soap Mesh Bag Body Facial Cleaning Tool,Must have with bars of soap ! You will love !,5.0,0.786824
2883,Dial Corp. 04303 Fels-Naptha Laundry Bar Soap (Pack of 8),Mom used this soap and I use it now too. This really works and is Essential for Laundry cleaning.,5.0,0.769150

QUERY: Small hair dryer

BM25 top results:

,product_title,text,rating,score
4112,JINRI Travel Hair Dryer 1875 Watt Dual Voltage Blow Dryer Dc Motor Foldable Handle Lightweight Negative Ionic Folding Hair Dryer (Black),Hairdryer is small and very compact. Good for guest room and my guest live it. Takes up little space and drys fast.,5.0,16.296875
18562,2 Pcs Home Portable Hair Dryer Diffuser Bonnet Attachment Salon Hairdryer Hair Diffuser Hair Dryer Bonnet Soft Cap Silver Pink,Love the bonnet. That piece works perfect. The tube part that connects to the blow dryer is a bit small. It didn't fit the blow drier I had. I had to find another compact one for it.,4.0,15.492961
12826,JINRI Travel Hair Dryer 1875 Watt Dual Voltage Blow Dryer Dc Motor Foldable Handle Lightweight Negative Ionic Folding Hair Dryer (Black),I absolutely love this hair dryer. It's cute and sleek and fits nicely in my travel bags. It has enough power to dry my which was something I was concerned about. I would recommend this item to an...,5.0,15.083106
6443,"Hair Dryers, Ionic 1875W Portable Hair Blow Dryer Intelligent Temperature Heat & Wind Speed Settings Technology, Negative Ion Hairdryer with AC Motor for Hair Care with Diffuser for Travel, Home","[[VIDEOID:efbc098d0c1d871b515eda2b6796d43d]] They hair dryer came securely packaged it can with a cute velvet travel size bag, It is a digital blow dryer so you can control the temperature on the ...",5.0,14.975512
3,"Jinri Professional Tourmaline Hair Dryer, Negative Ionic Blow Dryer with Concentrator, Lightweight Low Noise 1875W DC Motor Fast Dry Hair Blow Dryer","This Jinri hair dryer is among one of the best I have ever owned. Strong and powerful, my hair dries super quick. It has varying speeds and heat levels which allows me to dry and style my hair at ...",5.0,14.701050

Semantic search top results:

,product_title,text,rating,score
4943,2 Pcs Home Portable Hair Dryer Diffuser Bonnet Attachment Salon Hairdryer Hair Diffuser Hair Dryer Bonnet Soft Cap Silver Pink,"This thing is horrible. I can get over the fact that it didn't fit my hair dryer. I had to cut it to get it over the dryer nozzle, but the dang think kept blowing off my head. I had to sit the ...",1.0,0.774321
6443,"Hair Dryers, Ionic 1875W Portable Hair Blow Dryer Intelligent Temperature Heat & Wind Speed Settings Technology, Negative Ion Hairdryer with AC Motor for Hair Care with Diffuser for Travel, Home","[[VIDEOID:efbc098d0c1d871b515eda2b6796d43d]] They hair dryer came securely packaged it can with a cute velvet travel size bag, It is a digital blow dryer so you can control the temperature on the ...",5.0,0.737939
18885,JINRI Travel Hair Dryer 1875 Watt Dual Voltage Blow Dryer Dc Motor Foldable Handle Lightweight Negative Ionic Folding Hair Dryer (Black),"Very tiny and compact, but also quiet. My teenage son loves it!",5.0,0.732036
15029,"Jinri Professional Tourmaline Hair Dryer, Negative Ionic Blow Dryer with Concentrator, Lightweight Low Noise 1875W DC Motor Fast Dry Hair Blow Dryer",[[VIDEOID:64f556223f7fbc7bd5cf7d55b2557181]] This JINRI hairdryer is super lightweight and easy to hold. It has 1875 watts with 2 speeds and 3 temperatures. It also has a cool shot button that is ...,5.0,0.727992
4112,JINRI Travel Hair Dryer 1875 Watt Dual Voltage Blow Dryer Dc Motor Foldable Handle Lightweight Negative Ionic Folding Hair Dryer (Black),Hairdryer is small and very compact. Good for guest room and my guest live it. Takes up little space and drys fast.,5.0,0.637268

QUERY: The best air humidifer with essential oil

BM25 top results:

,product_title,text,rating,score
2340,"Sandalwood Essential Oil 100ML,100% Pure Organic Sandalwood Essential Oils for Aromatherapy, Diffuser, Massage, Skin Care, Bath","This is a pretty nice Vanilla fragrance oil. It is a fragrance oil or blend, not an essential oil. There's no such thing as vanilla essential oil. In the world of vanilla, there are vanilla absolu...",4.0,12.399124
16601,US Organic 100% Pure Peppermint Essential Oil - USDA Certified Organic - 10 ml Pack of 2 - w/Improved caps and droppers (More Size Variations Available),This is a good carrier oil for my essential oils! Very moisturizing. I wasn't sure if it would have it's own smell but it doesn't really. Seems like a good price for what you get.,5.0,11.627170
12938,US Organic 100% Pure Peppermint Essential Oil - USDA Certified Organic - 10 ml Pack of 2 - w/Improved caps and droppers (More Size Variations Available),This oil smells so good! Just like a geranium flower. I used it to make a roller ball of FCO and Geranium Oil to roll on my face. I also put two drops of the oil on a silk flower I have in my car....,5.0,10.794896
4404,US Organic 100% Pure Peppermint Essential Oil - USDA Certified Organic - 10 ml Pack of 2 - w/Improved caps and droppers (More Size Variations Available),"This Lavender essential oil seems very pure in aroma, consistency and color. It does have the botanical name Lavandula Angustifolia on the bottle and the USDA Certified Organic seal. If you want t...",5.0,10.759469
2773,Lemon Essential Oil 4 Oz - 5x Extra Strength 100% Pure & Natural Therapeutic Grade - Cold Pressed PREMIUM QUALITY Oil from Italy,This is a company I like to use for essential oils. I get some really nice products at really nice prices. I have tried alot of other companies but this one has some of the best quality oils I hav...,5.0,10.685654

Semantic search top results:

,product_title,text,rating,score
16447,"Sandalwood Essential Oil 100ML,100% Pure Organic Sandalwood Essential Oils for Aromatherapy, Diffuser, Massage, Skin Care, Bath",[[VIDEOID:837ed82f58e6aa8381af0ddfc97e2777]] This bottle has me smiling from ear to ear!! Smells sooo good! Arrived properly packaged and sealed no leaks!!! Bottle is HUGE!! Excellent value for wh...,5.0,0.787273
17204,"Top 8 Aromatherapy Essential Oil Starter Set- Peppermint, Tea Tree, Rosemary, Orange, Lemongrass, Lavender, Eucalyptus & Frankincense.8/10ml",really like it but....the oil is very light i use it in a oil diffuser and the smells are so soft i have to use a lot so beware they smell great but you will have to use a lot,3.0,0.785169
6518,"Aromyst Ultrasonic Glass Essential Oil Aromatherapy Diffuser, Black",I broke the first Aromyst I had by dropping it. I liked it so much I purchased another one instead of a different brand. I like the looks of the black diffuser as well as the options of a continuo...,5.0,0.774747
2533,"NEWSTYLE 700ml Large Capacity Aroma Atomizer Air Humidifier LED Ultrasonic Purifier Diffuser for Home, Office and Bedroom",This is a very small unit. Do not expect this to work as a home humidifier for anything but a small to medium size room. I bought it for my 90+ year old Dad's bedroom for the diffuser. He still...,4.0,0.744626
8410,Lemon Essential Oil 4 Oz - 5x Extra Strength 100% Pure & Natural Therapeutic Grade - Cold Pressed PREMIUM QUALITY Oil from Italy,I love the citrus essential oils because they brighten up the room and leave a freshness to the environment. I use this in my aromatherapy humidifier during the day. It smells great and I think ...,5.0,0.727725

QUERY: mineral sunscreen for babies

BM25 top results:

,product_title,text,rating,score
16667,Tangy Tangerine - 420 G Canister Single,"Dr. Wallach's products. This formula is similar to other high grade formulas except this one has something called &#34;rare earth&#34; in it, I believe. Translated that means trace minerals. No...",5.0,10.190047
16923,SOLARICARE 60 Cap Bottle 240mg 20:1 whole herb extract of polypodium leucotomos,Took it on trip to Cancun. Didn't notice anything different vs. not using it. Can't say whether it helped. The capsules were tiny and easy to swallow. No taste or ill effects.<br /><br />Used suns...,3.0,9.908568
11061,"Avon SKIN-SO-SOFT Bug Guard PLUS IR3535® Insect Repellent Moisturizing Lotion - SPF 30 Gentle Breeze, 4 oz",This seems to work well as both a sunscreen and sand flea repellent for my sensitive-skinned 5-yr.-old. He gets quite a painful burning sensation from some other sunscreens but is not bothered by ...,5.0,8.362735
8468,Daily's Min-Col® Fortè (250 Vegetarian Capsules),I have ordered these supplements several times. They always come quickly and are a very easily absorbed calcium with other trace minerals.,5.0,8.322886
8698,"North American Herb and Spice Mineral Supplement Purely-Min, 5 Ounce",I have been using a water machine to alkalize and purity the water for several years. My research shows that it removes many minerals along with the chlorine and fluoride which is why I purchased...,5.0,8.047409

Semantic search top results:

,product_title,text,rating,score
16923,SOLARICARE 60 Cap Bottle 240mg 20:1 whole herb extract of polypodium leucotomos,Took it on trip to Cancun. Didn't notice anything different vs. not using it. Can't say whether it helped. The capsules were tiny and easy to swallow. No taste or ill effects.<br /><br />Used suns...,3.0,0.977578
6269,"Avon SKIN-SO-SOFT Bug Guard PLUS IR3535® Insect Repellent Moisturizing Lotion - SPF 30 Gentle Breeze, 4 oz","I love this sunblock, we used it for 4 hours at/in the lake. No sunburn on my 5 year old or I. I usually use organic expensive sunscreens for him but I forgot them and this is all I had. It wor...",5.0,0.977444
8483,"Burt's Bees Baby Nourishing Lotion, Calming Baby Lotion - 6 Ounce Tube",This has done wonders in helping to heal my babies dry eczema prone skin! I alternate between this and mustella for eczema prone skin and now her skin is super soft and supple. No more dry flakey ...,5.0,0.938799
16503,"Bentonite, Hydrated (32 FL OZ)",Worked great,4.0,0.895416
8657,"Amazon Brand - Solimo Petroleum Jelly White Petrolatum Skin Protectant, Unscented, 7.5 Ounce","Love the price. I use this in every diaper change for my baby to prevent diaper rash. He’s been having an intolerance to certain things in my diet, and while I’m trying to figure out what the into...",5.0,0.851749

QUERY: hair spray that last more than 6 hours

BM25 top results:

,product_title,text,rating,score
12729,"Apalus Hair Straightening Brush, Fast Natural Straight Hair Styling, Anion Hair Care, Anti Scald, Massage Straightening Irons, Detangling Hair Brush","This brush is AMAZING! I have very thick color treated wavy shoulder length hair and I can honestly say that when I used this brush for the first time it only took me 10 minutes to straighten, ver...",5.0,13.020623
17106,FRIZZ EASE HAIR SPRAY,"After I style my hair, I’ve noticed this spray keeps it looking fuller all day. I have thick hair but this makes it appear to be twice it’s thickness. It keeps the style much longer than any oth...",5.0,11.884240
8317,"Automatic Curling Iron, Cordless Hair Curler with Adjustable Temperatures & Timers, Portable Auto Rotating Hair Curlers Wave Curling Wand, Rechargeable Ceramic Electric Hair Styling Tool","Dead On Arrival. I charged it for 8 hours at first, then tried it and it didn't turn on. The light turned on when it's charging so it wasn't the charger. I saw a Brad Mondo vid and his didn't t...",1.0,10.155206
15037,"CGR Anti Fog Spray for Glasses: (2pk) 2 oz Spray | Prevents Fog on All Lenses and Glasses, Sunglasses, Goggles, PPE | Safe on All Lenses | DEFOG it (2PK)",Was wondering how well this product would work but needed to use something whenever I would go out. Gave one bottle to my daughter-in-law to try out as well. She uses hers every day while at work....,5.0,9.981457
8579,"Hair Straightener, Flat Iron Steam Hair Straightener Nano Titanium Ceramic Tourmaline Flat Iron for Hair Travel Salon, 2 Inch White Professional Infrared Dual Voltage Hair Straightener by Megainvo",Its smells like my hair is always burning and the plates don't seem to keep my hair straight for more then a few hours,1.0,9.786347

Semantic search top results:

,product_title,text,rating,score
10333,10 Seconds - Disinfectant,"This stuff is quite strong, be sure to spray in a well ventilated area as it gives off a strong orange smell.",5.0,1.046064
17106,FRIZZ EASE HAIR SPRAY,"After I style my hair, I’ve noticed this spray keeps it looking fuller all day. I have thick hair but this makes it appear to be twice it’s thickness. It keeps the style much longer than any oth...",5.0,1.045197
12954,10 Seconds - Disinfectant,Tried different sprays and they only seemed to mask the smell. This spray kills the source of the odor. Just make sure you spray outside and dont breathe in the fumes. Leave outside to dry. Gre...,5.0,0.987821
8935,10 Seconds - Disinfectant,"It is pricey compared to other older eating sprays, but that's because it is what you'd expect for that higher price. I really appreciate that quality.",5.0,0.980955
12729,"Apalus Hair Straightening Brush, Fast Natural Straight Hair Styling, Anion Hair Care, Anti Scald, Massage Straightening Irons, Detangling Hair Brush","This brush is AMAZING! I have very thick color treated wavy shoulder length hair and I can honestly say that when I used this brush for the first time it only took me 10 minutes to straighten, ver...",5.0,0.950636

QUERY: Best Vitamins or supplements to take for pregnant women

BM25 top results:

,product_title,text,rating,score
2385,"Best Earth Naturals Vision Support Formula Supplement with Eye Vitamins, Lutein, Vitamin A, Quercetin and More - 30 Count","We were taking just the Lutein for our eyes and found this which has more beneficial ingreds for our ""older"" eyes :) The Lutein helps a lot but didn't know that Vit A, Zinc, Taurine, etc, were he...",4.0,10.515914
119,"Pink Stork Immune Support: Immunity Supplements + Vitamin C, Zinc Vitamins for Adults, Immunity Vitamins & Antioxidants, Cough & Cold Relief, Womens Multivitamin, Women-Owned, 60 Capsules","This is a good supplement with vitamin c, zinc, and magnesium along with a blend of herbs. The capsules are easy to swallow. Because of the magnesium, I take it at night since magnesium can make y...",4.0,9.916997
16662,"5X Potent B Complex Vitamin Supplement - Made in USA - All B Vitamins Including Vitamin B12, Folic Acid, B1, B2, B3, B5, B6, and B7 - Supplement for Energy, Stress, Brain Function and Immune Support",Good,5.0,9.915766
18720,"Pink Stork Immune Support: Immunity Supplements + Vitamin C, Zinc Vitamins for Adults, Immunity Vitamins & Antioxidants, Cough & Cold Relief, Womens Multivitamin, Women-Owned, 60 Capsules",I got this for my mom to help her get her immune system stronger since things are going crazy with the pandemic and the upcoming cold and flu season,5.0,9.885142
8620,"Hyland's - Calc. Fluor 6x, 500 Tablets","I was skeptical kinda, I feel it really works actually. I think this and evening primrose an magnesium citrate help me get pregnant. I had extreme infertility problems took 5 years to get pregnant...",5.0,9.748558

Semantic search top results:

,product_title,text,rating,score
6,"Amazon Elements Women’s One Daily Multivitamin, 59% Whole Food Cultured, Vegan, 65 Tablets, 2 month supply (Packaging may vary)","This is my new favorite daily vitamin. Totally Vegan, easy to swallow and fills all the daily requirements of my 60+aged body. I have a tendency to skip breakfast most days a week and this vitamin...",5.0,1.023650
37,"Amazon Elements Women’s One Daily Multivitamin, 59% Whole Food Cultured, Vegan, 65 Tablets, 2 month supply (Packaging may vary)","I just turned fifty recently and have been taking multi-vitamins for the last several years. This one is a large, &#34;horse pill&#34; type vitamin, but I haven't had any problems swallowing them....",5.0,1.010174
12871,"GNC Women's Ultra Mega Active, 180 ea","I love these vitamins. I've been taking these, or just the regular Women's Ultra Mega for almost 10 years now. I'm a stylist, and I have people ask me what they can take to help their hair grow. ...",5.0,0.961611
11035,LIBIDOX™ Hormone Balance for Women by Raw Fathers | Female Enhancement Pill - Female PMS PMDD Support | Herbal Vitamins for Women Health | 60 Capsules Made in USA,"I bought this to help with my hot flashes. It is definitely staying in my arsenal for my fight with menopause!<br /><br />I'm having a horrible time with hot flashes, and this has cut the amount i...",5.0,0.957951
16587,"Amazon Elements Women’s One Daily Multivitamin, 59% Whole Food Cultured, Vegan, 65 Tablets, 2 month supply (Packaging may vary)",I thought I would try. They are large so if you struggle to swallow big pills than these are not for you. The ingredients seem natural and quality but not sure how you really rate vitamins working...,4.0,0.937836

QUERY: equipments for stretching at home

BM25 top results:

,product_title,text,rating,score
6474,Dixie EMS Dixigear Empty First Responder II Bag,I bought 2 in different colors. One holds a nebulizer and all its parts in one place. The other holds personal home medical equipment. No more bulky boxes. The different colors helps separate ...,5.0,8.983292
6475,Dixie EMS Dixigear Empty First Responder II Bag,"I needed something to keep my medical stuff in at home. This is holding 2 BP machines, O2 meter, glucometer in the outer pockets plus a few other things. I like to be organized and have ""like"" t...",5.0,8.380817
12516,"BSN Medical Cover Roll Stretch, 2"" x 10 yds, Single Roll",Just what I need for under some stretch wraps,5.0,8.096906
10829,Quattro FX Full Face Headgear - Small - 61734,"Works like it should. I normally wear medium, but they stretch out pretty fast, so I bought the small, which almost didn't fit, but after it stretched out, now it is just right. Very tight to star...",5.0,7.621536
159,"BSN Medical Cover Roll Stretch, 2"" x 10 yds, Single Roll",Keeps my skin safe from the luekotape I put over the cover roll stretch tape,5.0,7.621536

Semantic search top results:

,product_title,text,rating,score
17283,"Tune Up Fitness – Alpha Twin Set in Tote | Larger Sized Yoga Massage Therapy Balls | Deep Precision Rolling, Myofascial Release and Pain Relief for Upper & Lower Back, IT Band, QL, Hamstrings, Glutes",The balls are great but they arrived used which is completely gross,1.0,0.881169
12484,"Back Stretcher, Lumbar Relief Back Stretcher, Back Stretcher for Pain Relief, Multi-Level Back Stretching Device, Lower Back Stretcher Device, Back Massage Stretcher with 3 Adjustable Settings…",Do a good job of allowing the back to stretch but it hurts.. the plastic pokes so use a towel!,4.0,0.865528
4293,"Tune Up Fitness – Alpha Twin Set in Tote | Larger Sized Yoga Massage Therapy Balls | Deep Precision Rolling, Myofascial Release and Pain Relief for Upper & Lower Back, IT Band, QL, Hamstrings, Glutes",Perfect. I bought these on the recommendation of Kelly Starrett from his book Ready to Run.<br />They are exactly what I wanted. Sturdy and well made.,5.0,0.859179
2599,"Lower Back Stretcher Spine Board-Back Stretcher for Lower Back Pain Relief, Back Cracking Device, Sciatica, Scoliosis, Spine Deck, on Bed,on Chair, Yoga Mat & Car-Spine Stretcher",This really gives a nice stretch. I use it on my office chair daily. Ever since I started using this the lower back pain I would have at the end of the day is gone.,5.0,0.859136
16567,"Back Massager, Aptoco Back Stretcher for Sciatica Relief, Herniated Disc/Spinal Stenosis-Back Massage Stretcher, Back Stretching Device",A little uncomfortable for me (not very flexable) but my wife loves it and uses it multiple times a day.,4.0,0.846901

QUERY: sunrise lamp that will help me to wake up in the morning

BM25 top results:

,product_title,text,rating,score
18956,Naturebright L6060 Per2 Led Daylight Lamp,"I tried the Phillips previously (see review there) but just couldn't get it to work. The NatureBright is easy to figure out, the controls make a lot more sense and you can easily see that it's se...",4.0,14.145717
4475,"5-hour ENERGY Shot, Regular Strength Orange, 1.93 oz., 24 pack",I got what I needed to wake up and get out to my commute while it's still dark. I am the poster child for &#34;not a morning person.&#34; This makes it happen.,5.0,12.930527
6350,"Sleep Mask for Women and Men,3D Contoured Eye Mask for Sleeping Mask Eye Cover,Lightweight Sleep Masks Blindfolds Eye Shade for Kids Girls Travel,2 Pack Black","Very comfortable, which surprised me! I love that it doesn't press against your eyes. I also suffer from extremely dry eyes, especially in the morning when I wake up, due to multiple fans running ...",5.0,12.274937
15081,"Verilux Original Natural Spectrum Deluxe Floor Lamp, Ivory",I had one of these lamps for several years and liked for reading. As I consider it a fairly expensive lamp I was disappointed when the switch quit working. I didn't get a response when I contact...,5.0,11.553884
16576,Indus Classic Pine Himalayan Salt Crystal Lamp Natural Ion Theray 2.25 Kg,"This was my first salt lamp. It is very well made, interesting to look at and a nice solid size. It lights up really well. The photo on amazon doesn't do it justice IMO and makes it look like t...",5.0,11.356824

Semantic search top results:

,product_title,text,rating,score
18743,"Verilux Original Natural Spectrum Deluxe Floor Lamp, Ivory","I was sitting on my bed last night doing some embroidery and I noticed that I really needed some more light on the ""subject."" My hubby reminded me that I had the Verilux lamp still in the box tha...",5.0,1.059190
2847,"Verilux Original Natural Spectrum Deluxe Floor Lamp, Ivory","I bought this as a gift for my mom, it was at the very least a bit of a pain to put together and cheaply made. It required electrical tape and a good bit of cursing! Is now working ok. The gril...",4.0,1.023793
16576,Indus Classic Pine Himalayan Salt Crystal Lamp Natural Ion Theray 2.25 Kg,"This was my first salt lamp. It is very well made, interesting to look at and a nice solid size. It lights up really well. The photo on amazon doesn't do it justice IMO and makes it look like t...",5.0,1.013871
2796,Naturebright L6060 Per2 Led Daylight Lamp,"This functions well as daylight alarm. It's best feature is that the LED's arc out over the bed and shine down, as opposed to other models which shine straight out horizontally, which means you ha...",3.0,0.727630
18956,Naturebright L6060 Per2 Led Daylight Lamp,"I tried the Phillips previously (see review there) but just couldn't get it to work. The NatureBright is easy to figure out, the controls make a lot more sense and you can easily see that it's se...",4.0,0.675205

QUERY: Something to relieve my back pain

BM25 top results:

,product_title,text,rating,score
491,"Neck Stretcher Cervical Neck Traction Device Over Door for Home Use,Portable Neck Traction for Neck Pain Relief, Physical Therapy AIDS for Neck Spine Decompressor (Black)",First time user. It took me a while a find out how to assemble them. After some adjustments I find a way to use it. And it does helps relieve my neck pain.,5.0,10.952530
12649,Shoulder Wrap Gel Ice Hot Cold Pack for Shoulder Injury Pain Relief Therapy Rotator Cuff Rheumatoid Arthritis Treatment Osteoarthritis Bursitis Tendinitis AC Joint Sports Injuries,"I use it alot, great product, helps relieve my muscle pain.",5.0,10.870432
14553,"ZSZBACE Posture Corrector Back Brace for Men and Women- Relieve Back Pain, Align Spain, Correct Kyphosis (XXL)",It help with my back pain,5.0,10.828765
671,Korean Red Ginseng Patch Powerstrip Energy Pain Relief - 20 Patches,These patches really do relieve the pain. They can be cut to whatever size you need.They stick extremely well.,5.0,10.687405
6944,"Real Time Pain Relief George Foreman's Knockout Formula, 1 Oz GoPak",This stuff does exactly what it says it will do. Relieve pain and make you feel better. Happy!,5.0,10.650396

Semantic search top results:

,product_title,text,rating,score
10646,"REEHUT Foam Roller - (6""x36"") Firm High-Density Muscle Rollers for Deep Tissue Muscle Massage Trigger Point for Pain Relief & Pilates with User E-Book (90cm)","Is what your back muscles and spine will say!<br />Be smart, use as advised. Made of dark grey/black Styrofoam.",5.0,0.847140
2599,"Lower Back Stretcher Spine Board-Back Stretcher for Lower Back Pain Relief, Back Cracking Device, Sciatica, Scoliosis, Spine Deck, on Bed,on Chair, Yoga Mat & Car-Spine Stretcher",This really gives a nice stretch. I use it on my office chair daily. Ever since I started using this the lower back pain I would have at the end of the day is gone.,5.0,0.810345
12300,"Genericb Back Massage Stretcher Arch Magic Message Stretcher Back Stretcher Lumbar Support Device, Lower and Upper Back Pain Relief Relax Mate Spine Pain Relief Chiropractic",A little to stiff for sore back muscles. need to use a soft pad with it,4.0,0.758031
2628,"Acupuncture Mat and Pillow Set-Relieve Your Stress, Back, Neck, and Sciatic Pain(99% Cotton Fabric, Plastic Spikes and Foam core) Green",Really helped with tension in my shoulders!,5.0,0.709054
4439,"Large Heating and Cooling Reusable Wrap by Soothing Company for Back Pain, Stomach Cramps, Sore Neck, Shoulders, Legs, Joint and Muscle Pain Hot and Cold Therapy to Support Healing Injuries",This absolutely what I have been looking for to use for my low back.,5.0,0.699777